### ISSUE TITLE
connectionScopes respected?

### ISSUE THREAD

**Issue by dbinetti** [seawatts/ember-simple-auth-auth0#12]
Thanks for working on this library.  I spoke at length with Eugenio Pace, Auth0's co-founder and CEO. Unfortunately Ember isn't high on their priority list, so your efforts here are most appreciated.

On my issue, I see now that v 2.0.0 is hot off the press, but do you see anything with my config below that would cause the library not to pass the `connectionScopes` options?  It doesn't appear to be getting to Auth0...

thanks

```
    login () {
      var lockOptions = {
        autoclose: true,
        auth: {
          redirect: false,
          connectionScopes: {
            'google-oauth2': [
              'profile',
              'https://www.googleapis.com/auth/drive.photos.readonly',
            ]
          },
          params: {
            access_type: 'offline',
            prompt: 'consent',
          }
        },
      };
      this.get('session').authenticate('authenticator:auth0-lock', lockOptions);
    },
```

**Comment by seawatts** [comment]
Thanks! I love ember so it's no big deal. I'd love feedback you, or the
founders have.

As far as connectionScopes it looks like it was added in lock.js v10.5.0.
Which version is in your bower.json file?

**Comment by dbinetti** [comment]
that would be
```
"auth0-lock": "^10.0.2",
```

seems like I'm a tad out of date!

thanks for the pointer


so far, it's working for me, modulo this issue.  so i'll give it a whirl

I told him to just merge your stuff over... :-)

in the end it's easy enough to fork, but i just said it makes Auth0 look
bad.  he knows, of course, they are just hair-on-fire like any startup.

**Comment by seawatts** [comment]
Yeah the only reason I didn't fork was because I wanted to change quite a
bit of stuff and it ended up refactoring the whole thing. Also they
couldn't get a hold of the publisher of their add-on so they couldn't
publish to npm. I never intended to make them look bad. I'd be happy to
help them merge this over.

**Comment by dbinetti** [comment]
oh, interesting.  well i'll bring that up the next time i speak with him.
 thanks again!

BTW, upgrading the dependencies worked....

**Comment by seawatts** [comment]
Awesome! I'll close this out.
