### ISSUE TITLE
accessing the `state` parameter value

### ISSUE THREAD

**Issue by dbinetti** [seawatts/ember-simple-auth-auth0#22]
I searched the code and can't find any reference to the `state` param.  Is this supported?

**Comment by seawatts** [comment]
Yeah, it doesn't look like we are parsing this out of the return url. I was thinking about parsing it out and then putting it in the authenticated block on the session.

**Comment by seawatts** [comment]
Just adding some notes on documentation 
https://auth0.com/docs/libraries/lock/v10/sending-authentication-parameters#state-string-
https://auth0.com/docs/tutorials/redirecting-users
https://auth0.com/docs/protocols/oauth2/oauth-state

**Comment by dbinetti** [comment]
So this *is* being done (whether you like it or not!) :-P    I was simply looking in the wrong place....

**Comment by seawatts** [comment]
Where did you find it?

**Comment by dbinetti** [comment]
On the session authenticated object
