### ISSUE TITLE
Auth0 not playing nicely with Phantomjs in ember test and CI

### ISSUE THREAD

**Issue by FrancoB411** [seawatts/ember-simple-auth-auth0#25]
Acceptance tests run fine in `localhost:4400/tests`.
But `ember test` and Codeship CI error out with:
`Built project successfully. Stored in "Users/.../tests_dist-qlMhYAfG.tmp".
not ok 1 PhantomJS 1.9 - Global error: TypeError: 'undefined' is not a function (evaluating 'ReactElement.createElement.bind(null, type)') at http:
//localhost:4401/assets/vendor.js, line 135461`

We are not using react. Lock's `package.json` on the other hand...
```
    "react": "^15.0.0 || ^16.0.0",
    "react-addons-css-transition-group": "^15.0.0 || ^16.0.0",
    "react-dom": "^15.0.0 || ^16.0.0",
```

We are using magic links, is there a clean way to use ember-simple-auth-auth0 without using lock?

Thanks.

**Comment by FrancoB411** [comment]
Update:

Upgrading phantom.js to from 1.9.8 to 2.1.1 , and configuring CI to use 2.1.1 solved the problem!

**Comment by seawatts** [comment]
👍
