### ISSUE TITLE
Auth0-Lock > 10.8.1 - idTokenPayload is missing

### ISSUE THREAD

**Issue by cs3b** [seawatts/ember-simple-auth-auth0#38]
Lack of `idTokenPayload.exp` and `exp` in `session.data.authenticated` lead to token invalidation right after successful auth.

Not sure why, but Auth0-Lock is returning `expires` value that is  86400 (24 hours) and it is pretty weird (and there is no `exp`, neither `idTokenPayload`). 

Downgrading to 10.8.1 is the solution, still it looks like we would need to have `auth0-try` :-) (similar to ember-try) to test library against even minor versions of auth0 and auth0-lock ...

**Comment by seawatts** [comment]
I can't seem to reproduce this locally. I do agree with creating an auth0-try scenario! see #39

**Comment by cs3b** [comment]
Thank your for the update @seawatts :-) #41 

I've updated my app with the recent master version, libs are working perfectly fine, everything is loading. Still I have the issue with being logout right after the successful authentication. 

Below I've attached my environment, and what the session data look like, just before session is getting expired. So far I'm thinking that the problem is with lack of `idTokenPayload` (that was present in auth0 < 8.0) 

````ruby
const deprecatedExp = getWithDefault(this, 'session.data.authenticated.exp', null);
const newExp = getWithDefault(this, 'session.data.authenticated.idTokenPayload.exp', null);
````
https://github.com/seawatts/ember-simple-auth-auth0/blob/develop/addon/mixins/application-route-mixin.js#L154

![screen shot 2017-02-15 at 21 58 31](https://cloud.githubusercontent.com/assets/120829/22995218/52ccdac8-f3ca-11e6-829f-adb13c949165.jpg)

````json
{
  "authenticated": {
    "authenticator": "authenticator:auth0-lock",
    "accessToken": "***",
    "expiresIn": 86400,
    "idToken": "***",
    "tokenType": "Bearer",
    "state": "***",
    "profile": {
      "email": "m.czyz@selleo.com",
      "name": "Michał Czyż",
      "given_name": "Michał",
      "family_name": "Czyż",
      "picture": "https://lh6.googleusercontent.com/-6ahGuaH4y6A/AAAAAAAAAAI/AAAAAAAAABE/4ZL4wBDvIaI/photo.jpg",
      "gender": "male",
      "locale": "pl",
      "nickname": "m.czyz",
      "email_verified": true,
      "clientID": "***",
      "updated_at": "2017-02-15T20:57:45.509Z",
      "user_id": "google-oauth2|***",
      "identities": [
        {
          "provider": "google-oauth2",
          "user_id": "***",
          "connection": "google-oauth2",
          "isSocial": true
        }
      ],
      "created_at": "2017-02-06T12:33:02.661Z",
      "global_client_id": "***"
    }
  }
}
````

**Comment by seawatts** [comment]
Make sure you are on the develop branch not master.

**Comment by cs3b** [comment]
My mistate, yes I'm using the latest develop branch - here is what I've from my package.json
````json
    "ember-simple-auth-auth0": "git://github.com/seawatts/ember-simple-auth-auth0.git#e9986a0b013c05c06818e647e1f9b8c2f4b32402",
````

**Comment by seawatts** [comment]
I've released a new version. Can you see if that fixes the issue. https://github.com/seawatts/ember-simple-auth-auth0/releases/tag/v2.3.0

**Comment by seawatts** [comment]
I'm actually now seeing this. It is weird. It seems to only happen when you don't perform a full logout through auth0

**Comment by seawatts** [comment]
I'm actually seeing this now. It seems like when you do a full logout it returns the correct idTokenPayload. But when you do a partial logout. i.e. just clear your ember-simple-auth session from local storage then it doesn't fill it back in and only gives you `expiresIn`

**Comment by cs3b** [comment]
I've tested v2.3.0, and the same behaviour, I try to clear fully local storage, still give the same results (session is invalidated right after authentication)  

For me it looks like the Auth0 change the api - still I might be wrong. 

Could you tell me more, what do you understand by `partial logout` ?

**Comment by cs3b** [comment]
I've updated to 3.0.0 and read the breaking changes :-( Still somehow understood.
