### ISSUE TITLE
Are the setup instructions the same as auth0-ember-simple-auth ?

### ISSUE THREAD

**Issue by Floby** [seawatts/ember-simple-auth-auth0#4]
I tried this addon after failing to make things work with `auth0-ember-simple-auth` which seems as official as unmaintained and currently doesn't work with Ember2 (not using the latest version of simple-auth).

However I couldn't manage to get things to work with this one either and i was wondering if the setup was very different from the one described [here](https://auth0.com/docs/quickstart/spa/emberjs) for example.

My main issue is that I can get to the point of a callback actually being sent to my app with a url like `http://localhost:4200/sign_in#access_token=<XXX>&id_token=<XXX>` but nothing happens next, the session is not updated with the new identity

**Comment by mrship** [comment]
For me, the missing part was to register the Jwt authorizer as well as the Authenticator that this addon provides. So in a custom initializer:

```
import Authenticator from 'my-app/authenticators/auth0-lock';
import Jwt from 'my-app/authorizers/jwt';

export default {
  name:   'custom-lock',
  before: 'ember-simple-auth',
  initialize: function(registry) {
    registry.register('simple-auth-authenticator:lock', Authenticator);
    registry.register('simple-auth-authorizer:jwt', Jwt);
  }
};
```

This appears to be [done automatically](https://github.com/auth0/auth0-ember-simple-auth/blob/master/app/initializers/auth0-ember-simple-auth-initializer.js) for you in the "official" plugin, but not in this one.

**Comment by Floby** [comment]
Hey, thanks for your reply,

On my side, I identified, that I just needed to change a few things from the doc I previsouly linked

1. ember-simple-auth need to be installed with `ember install ember-simple-auth`
2. there is no `ember generate scaffold-auth0`
3. imports must be changed from `simple-auth/...` to `ember-simple-auth/...`
4. authorizers are now looked up by ember simple auth as `authorizer:<name>` instead of `simple-auth-authorizer:<name>`


I isolated the problem to ember-simple-auth-auth0 never getting [the callback from Lock](https://github.com/seawatts/ember-simple-auth-auth0/blob/develop/addon/authenticators/auth0-lock.js#L137-L149) when authentication is finished. This is due to the fact that a full refresh of the page happens and the context is therefore lost.

Maybe an initializer could be added which parses the hash of the URL with Lock.js in order to seek for an `access_token` and an `id_token` ?

**Comment by seawatts** [comment]
Hey, thanks for the feedback. This addon should be feature parody and more than the official one. Sorry I have not updated the docs. We are currently using this in production at our company so I'll try to get the docs up to date sometime this week.

**Comment by Floby** [comment]
Great! Looking forward to seeing it working :)

In the meantime, I have also poked at auth0 on both Twitter and customer support about them not maintaining the "official" addon. Let's what this does...

One useful thing to have would be an example app that demonstrate how things are done. Bu

**Comment by Floby** [comment]
Great! Looking forward to seeing it working :)

In the meantime, I have also poked at auth0 on both Twitter and customer
support about them not maintaining the "official" addon. But I'll choose
whatever works first.

**Comment by reedyrm** [comment]
I'm running into the same issue where the authenticated event doesnt fire the first time and reloads the page with the 

> http://localhost:4200/sign_in#access_token=<XXX>&id_token=<XXX> 

If I press the login button again, the authenticated event will fire and it will load the user and bring them into the app as authenticated.  It would be great to see a working example of this of this library.  And thanks for making this addon and bringing it up to speed!

**Comment by seawatts** [comment]
@mrship this addon is setup a little differently. You don't actually have to inject the authenticator or authorizer. 
You should just be able to use it by default with the way that ember-simple-auth tries to find the authenticators.
```js
get(this, 'session').authenticate('authenticator:auth0-lock', lockOptions);
````

@Floby I am now including ember-simple-auth during the installation stage of this addon now.

@reedyrm I can't seem to replicate this. Can you create a new issue with repo steps. Thanks.

I have added more docs to the README and I'll release a new version soon. It will be a major version bump seeing as there are breaking changes.

**Comment by Floby** [comment]
@seawatts that's a plus =) great

@reedyrm I solved the problem by using an option I found in [this file](https://github.com/seawatts/ember-simple-auth-auth0/blob/master/tests/dummy/app/controllers/login.js#L13-L21) for a dummy app used for tests. The lock options used there are:
```javascript
      {
        autoclose: true,
        auth: {
          redirect: false,
          params: {
            scope: 'openid'
          }
        }
      }
```
I think the `redirect: false` is what was missing in my initial attempts. Now lock opens a (mostly blank) popup window which is used for the redirect instead of the main one, locks is able to extract the token and close the popup pretty quickly.

@seawatts Maybe this option should be the default, since it doesn't seem to work otherwise? Or setup an initializer which could extract the token from the URL upon redirect before the app is initialized.

**Comment by seawatts** [comment]
@Floby interesting, I think I'd rather go with including `redirect: false` by default instead of trying to extract it out of the url myself, even though that is what I have to do when impersonating.

**Comment by Floby** [comment]
I haven't tried impersonation yet, but I know I'll need it soon. Is there
some trick to it?

**Comment by seawatts** [comment]
@Floby I updated the readme with how to do impersonation
