### ISSUE TITLE
Quick Start doesn't seem to work.

### ISSUE THREAD

**Issue by angelosarto** [seawatts/ember-simple-auth-auth0#44]
I tried to create the simplest example possible and I ran across a few issues:

1.  I started with a blank `ember new app`
1.  I did `ember install ember-simple-auth-auth0`
1.  I added the route, controller and template code
1.  I encountered the issue with newer auth0.js so I locked bower version to 7.6.0 and bower installed it.
1.  The lock component loads, and I can login, after a successful login the url contains the JWT 
> localhost:4200/#access_token=ey...
1. however I the session doesn't seem to be present in the template - as it still shows login.

Is there some step I missed?

**Comment by seawatts** [comment]
Can you try with the new version https://github.com/seawatts/ember-simple-auth-auth0/releases/tag/v2.3.0

**Comment by seawatts** [comment]
Closing. Cannot reproduce.

**Comment by angelosarto** [comment]
SOrry for the delay -- got back and tried this today.  Seeing a similar issue - added a new separate issue.
