### ISSUE TITLE
Bower requirement for auth0.js

### ISSUE THREAD

**Issue by mrship** [seawatts/ember-simple-auth-auth0#5]
As I understand it, `auth0.js` is included with `auth0-lock`, so I'm unsure why the addon adds it as a separate bower dependency. Is that so that their versions can be controlled separately?

This caught me out because installing the addon didn't actually add the correct bower dependencies (I'm unsure as to why), so my app wouldn't build until I explicitly added both `auth0-lock` _and_ `auth0.js` in `bower.json`.

Could `auth0.js` be removed as  dependency and make this build process just use `auth0-lock`?

Also, thanks for putting this addon together; we've finally been able to upgrade to v10, and add impersonation support and social login via redirects - great work!

**Comment by seawatts** [comment]
Hey, the requirement is so that you don't have to add it yourself and so that you can control your own version if you want to bump it. I will check to see why it is not adding it correctly.

**Comment by seawatts** [comment]
The reason I am including the auth0.js library is so that I can parse out the access_token when you are trying to impersonate a user in the url.
