### ISSUE TITLE
ember-simple-auth-auth0 camelcase breaking ember-simple-auth Oauth2 authorizer?

### ISSUE THREAD

**Issue by maxigs** [seawatts/ember-simple-auth-auth0#51]
I'm currently trying to get started using Auth0 and EmberJS and after a while of trying to figure out why i'm unable to authorize API requests from my EmberJS app i figured out an inconsistency between `ember-simple-auth-auth0` and `ember-simple-auth`.
Since i'm just a beginner in both i'm not sure if this is actually a bug:

The core part of Oauth2Bearer Authorizer vom `ember-simple-auth` looks like this
```
authorize(data, block) {
    const accessToken = data['access_token'];

    if (!isEmpty(accessToken)) {
      block('Authorization', `Bearer ${accessToken}`);
    }
  }
```
Depending on the attribute `access_token` in the authentication data.

However `ember-simple-auth-auth0` converts this to `accessToken`, as it even states in the README, "Note: all keys coming back from auth0 are transformed to camelcase for consistency".

I managed to fix the issue in my code now, not sure if it's a general bug or expected behavior.

**Comment by seawatts** [comment]
Yeah, I was not sure what I should do about this. Maybe I should change it back.

**Comment by seawatts** [comment]
Also you should be using the `authorizer:jwt` which ships with this addon.

**Comment by maxigs** [comment]
Ah i didn't see that one before. I see you added it to the readme now too :)

May i ask what the reason for changing to camelcase was in the first place? I know it's more JS-Style than underscores, but if you build a plugin for something i would go with it's style, and not introduce inconsistencies that will turn into problems sooner or later.
Like now duplicating essentially the same code just with one "_" missing in the whole file.

**Comment by seawatts** [comment]
I am actually not changing it sorry. I'm passing it directly in from what I get back from auth0.

Closing
