### ISSUE TITLE
where does semver bower dependency come from?

### ISSUE THREAD

**Issue by JackCA** [seawatts/ember-simple-auth-auth0#53]
Hi there -- I just did some upgrading from a previous version and ran into this error when starting my dev server:
```
Livereload server on http://localhost:49153
Serving on http://localhost:4200/
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, open '[...]/tmp/source_map_concat-input_base_path-b5rQE7hb.tmp/bower_components/semver/semver.browser.js'
```

and I'm noticing there's a reference to importing the `semver` bower package [here](https://github.com/seawatts/ember-simple-auth-auth0/blob/e9986a0b013c05c06818e647e1f9b8c2f4b32402/index.js#L15)

Is this supposed to be installed by this addon itself? I manually added it to my bower.json and now everything is working, but still confused as to why it was missing.

Let me know if you need any other info

**Comment by seawatts** [comment]
Yeah I introduced this the other day to check to see if the user is using auth0.js < 8.x.x However, I'm going to take it out and just do a manual compare.

**Comment by JackCA** [comment]
@seawatts nice! 😄
