### ISSUE TITLE
"Nonce does not match" - error on login

### ISSUE THREAD

**Issue by seacaptain** [seawatts/ember-simple-auth-auth0#61]
When logging in I receive an error "Encountered an error from auth0 - invalid_token -- Nonce does not match." Refreshing the page seems to fix the issue and login proceeds as expected.

I'm using RS256, logging in from root page and returning to root page, all other settings are the same as the example specifies.

Ember 2.11.0
auth0-lock 10.11.0
auth0.js 8.2.0
ember-simple-auth 1.2.0
ember-simple-auth-auth0 3.0.0

Recent activity here which may well be related:
https://github.com/auth0/auth0.js/issues/365

**Comment by seawatts** [comment]
Closing here. Looks like this got fixed on their end.
https://github.com/auth0/auth0.js/pull/382

**Comment by sukima** [comment]
This is still happening to me. Why is it still happening?

**Comment by sukima** [comment]
auth0/auth0.js#382 **merged** March 91th 2017:

![screen shot 2017-05-05 at 21 42 54](https://cloud.githubusercontent.com/assets/70075/25768967/c18fecd4-31dc-11e7-81a7-0aef9a14ae93.png)

`auth0.js` released to version `8.6.0` on April 24th 2017:

![screen shot 2017-05-05 at 21 43 33](https://cloud.githubusercontent.com/assets/70075/25768992/43ecb37e-31dd-11e7-8aeb-141fa71e1b33.png)

Blueprint generator for `ember-simple-auth-auth0` adds version `^8.6.0`:

<img width="363" alt="screen shot 2017-05-05 at 21 40 11" src="https://cloud.githubusercontent.com/assets/70075/25769010/78aa1ed0-31dd-11e7-8542-e604f0452073.png">
